// Code generated by go-swagger; DO NOT EDIT.

package write

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/keto/internal/httpclient/models"
)

// DeleteRelationTuplesReader is a Reader for the DeleteRelationTuples structure.
type DeleteRelationTuplesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRelationTuplesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteRelationTuplesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRelationTuplesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRelationTuplesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRelationTuplesNoContent creates a DeleteRelationTuplesNoContent with default headers values
func NewDeleteRelationTuplesNoContent() *DeleteRelationTuplesNoContent {
	return &DeleteRelationTuplesNoContent{}
}

/* DeleteRelationTuplesNoContent describes a response with status code 204, with default header values.

An empty response
*/
type DeleteRelationTuplesNoContent struct {
}

func (o *DeleteRelationTuplesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /admin/relation-tuples][%d] deleteRelationTuplesNoContent ", 204)
}

func (o *DeleteRelationTuplesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRelationTuplesBadRequest creates a DeleteRelationTuplesBadRequest with default headers values
func NewDeleteRelationTuplesBadRequest() *DeleteRelationTuplesBadRequest {
	return &DeleteRelationTuplesBadRequest{}
}

/* DeleteRelationTuplesBadRequest describes a response with status code 400, with default header values.

genericError
*/
type DeleteRelationTuplesBadRequest struct {
	Payload *models.GenericError
}

func (o *DeleteRelationTuplesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /admin/relation-tuples][%d] deleteRelationTuplesBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteRelationTuplesBadRequest) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteRelationTuplesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRelationTuplesInternalServerError creates a DeleteRelationTuplesInternalServerError with default headers values
func NewDeleteRelationTuplesInternalServerError() *DeleteRelationTuplesInternalServerError {
	return &DeleteRelationTuplesInternalServerError{}
}

/* DeleteRelationTuplesInternalServerError describes a response with status code 500, with default header values.

genericError
*/
type DeleteRelationTuplesInternalServerError struct {
	Payload *models.GenericError
}

func (o *DeleteRelationTuplesInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /admin/relation-tuples][%d] deleteRelationTuplesInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteRelationTuplesInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteRelationTuplesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
