/*
 * Package main ORY Keto
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type IntrospectionResponse struct {
	Active bool `json:"active,omitempty"`

	Aud []string `json:"aud,omitempty"`

	ClientId string `json:"client_id,omitempty"`

	Exp int64 `json:"exp,omitempty"`

	// Session represents arbitrary session data.
	Ext map[string]interface{} `json:"ext,omitempty"`

	Iat int64 `json:"iat,omitempty"`

	Iss string `json:"iss,omitempty"`

	Nbf int64 `json:"nbf,omitempty"`

	Scope string `json:"scope,omitempty"`

	// Here, it's sub
	Sub string `json:"sub,omitempty"`

	TokenType string `json:"token_type,omitempty"`

	Username string `json:"username,omitempty"`
}
