linters:
  disable-all: true
  enable:
    - gosec
    - goimports
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/ory/keto
