linters:
  disable-all: true
  enable:
    - gosec
    - goimports
    - deadcode
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck

linters-settings:
  goimports:
    local-prefixes: github.com/ory/keto
