# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: keto

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go install github.com/gobuffalo/packr/packr
    - packr

builds:
  -
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/ory/keto/cmd.Version={{.Env.RELEASE_NAME}} -X github.com/ory/keto/cmd.Commit={{.FullCommit}} -X github.com/ory/keto/cmd.Date={{.Date}}
    binary: keto
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  -
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brew:
  github:
    owner: ory
    name: homebrew-keto
  homepage:  https://www.ory.sh
  commit_author:
    name: ory
    email: hi@ory.sh

scoop:
  bucket:
    owner: ory
    name: scoop-keto
  homepage:  https://www.ory.sh
  commit_author:
    name: ory
    email: hi@ory.sh

dockers:
  - image_templates:
      - "oryd/keto:v{{ .Major }}"
      - "oryd/keto:v{{ .Major }}.{{ .Minor }}"
      - "oryd/keto:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/keto:{{ .Env.DOCKER_SHORT_TAG }}"
      - "oryd/keto:latest"

release:
  prerelease: auto
  name_template: "{{.Env.RELEASE_NAME}}"
