- op: add
  path: /info
  value:
    title: Ory Keto API
    description: |
      Documentation for all of Ory Keto's REST APIs. gRPC is documented separately.
    version: >-
      {{ getenv "CIRCLE_TAG" }}
    license:
      name: Apache 2.0
    contact:
      email: "hi@ory.sh"
