// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ory/keto/opl/v1alpha1/syntax_service.proto

package opl

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParseErrors   []*ParseError          `protobuf:"bytes,1,rep,name=parse_errors,json=parseErrors,proto3" json:"parse_errors,omitempty"`
	Errors        []*ParseError          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetParseErrors() []*ParseError {
	if x != nil {
		return x.ParseErrors
	}
	return nil
}

func (x *CheckResponse) GetErrors() []*ParseError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ParseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Start         *SourcePosition        `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *SourcePosition        `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseError) Reset() {
	*x = ParseError{}
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseError) ProtoMessage() {}

func (x *ParseError) ProtoReflect() protoreflect.Message {
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseError.ProtoReflect.Descriptor instead.
func (*ParseError) Descriptor() ([]byte, []int) {
	return file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescGZIP(), []int{2}
}

func (x *ParseError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseError) GetStart() *SourcePosition {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ParseError) GetEnd() *SourcePosition {
	if x != nil {
		return x.End
	}
	return nil
}

type SourcePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          uint32                 `protobuf:"varint,1,opt,name=line,json=Line,proto3" json:"line,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcePosition) Reset() {
	*x = SourcePosition{}
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcePosition) ProtoMessage() {}

func (x *SourcePosition) ProtoReflect() protoreflect.Message {
	mi := &file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcePosition.ProtoReflect.Descriptor instead.
func (*SourcePosition) Descriptor() ([]byte, []int) {
	return file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescGZIP(), []int{3}
}

func (x *SourcePosition) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourcePosition) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

var File_ory_keto_opl_v1alpha1_syntax_service_proto protoreflect.FileDescriptor

const file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDesc = "" +
	"\n" +
	"*ory/keto/opl/v1alpha1/syntax_service.proto\x12\x15ory.keto.opl.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"(\n" +
	"\fCheckRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\x90\x01\n" +
	"\rCheckResponse\x12D\n" +
	"\fparse_errors\x18\x01 \x03(\v2!.ory.keto.opl.v1alpha1.ParseErrorR\vparseErrors\x129\n" +
	"\x06errors\x18\x02 \x03(\v2!.ory.keto.opl.v1alpha1.ParseErrorR\x06errors\"\x9c\x01\n" +
	"\n" +
	"ParseError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12;\n" +
	"\x05start\x18\x02 \x01(\v2%.ory.keto.opl.v1alpha1.SourcePositionR\x05start\x127\n" +
	"\x03end\x18\x03 \x01(\v2%.ory.keto.opl.v1alpha1.SourcePositionR\x03end\"<\n" +
	"\x0eSourcePosition\x12\x12\n" +
	"\x04line\x18\x01 \x01(\rR\x04Line\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column2\xbc\x03\n" +
	"\rSyntaxService\x12\xaa\x03\n" +
	"\x05Check\x12#.ory.keto.opl.v1alpha1.CheckRequest\x1a$.ory.keto.opl.v1alpha1.CheckResponse\"\xd5\x02\x92A\xaf\x02\n" +
	"\frelationship*\x0echeckOplSyntax2\n" +
	"text/plain:\x10application/jsonJS\n" +
	"\x03200\x12L\n" +
	" The result of the syntax checker\x12(\n" +
	"&\x1a$.ory.keto.opl.v1alpha1.CheckResponseJK\n" +
	"\x03400\x12D\n" +
	"\ferrorGeneric\x124\n" +
	"2\x1a0.ory.keto.relation_tuples.v1alpha2.ErrorResponseJO\n" +
	"\adefault\x12D\n" +
	"\ferrorGeneric\x124\n" +
	"2\x1a0.ory.keto.relation_tuples.v1alpha2.ErrorResponse\x82\xd3\xe4\x93\x02\x1c:\acontent\"\x11/opl/syntax/checkB\x95\x01\n" +
	"\x18sh.ory.keto.opl.v1alpha1B\x12SyntaxServiceProtoP\x01Z3github.com/ory/keto/proto/ory/keto/opl/v1alpha1;opl\xaa\x02\x15Ory.Keto.Opl.v1alpha1\xca\x02\x15Ory\\Keto\\Opl\\v1alpha1b\x06proto3"

var (
	file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescOnce sync.Once
	file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescData []byte
)

func file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescGZIP() []byte {
	file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescOnce.Do(func() {
		file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDesc), len(file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDesc)))
	})
	return file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDescData
}

var file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ory_keto_opl_v1alpha1_syntax_service_proto_goTypes = []any{
	(*CheckRequest)(nil),   // 0: ory.keto.opl.v1alpha1.CheckRequest
	(*CheckResponse)(nil),  // 1: ory.keto.opl.v1alpha1.CheckResponse
	(*ParseError)(nil),     // 2: ory.keto.opl.v1alpha1.ParseError
	(*SourcePosition)(nil), // 3: ory.keto.opl.v1alpha1.SourcePosition
}
var file_ory_keto_opl_v1alpha1_syntax_service_proto_depIdxs = []int32{
	2, // 0: ory.keto.opl.v1alpha1.CheckResponse.parse_errors:type_name -> ory.keto.opl.v1alpha1.ParseError
	2, // 1: ory.keto.opl.v1alpha1.CheckResponse.errors:type_name -> ory.keto.opl.v1alpha1.ParseError
	3, // 2: ory.keto.opl.v1alpha1.ParseError.start:type_name -> ory.keto.opl.v1alpha1.SourcePosition
	3, // 3: ory.keto.opl.v1alpha1.ParseError.end:type_name -> ory.keto.opl.v1alpha1.SourcePosition
	0, // 4: ory.keto.opl.v1alpha1.SyntaxService.Check:input_type -> ory.keto.opl.v1alpha1.CheckRequest
	1, // 5: ory.keto.opl.v1alpha1.SyntaxService.Check:output_type -> ory.keto.opl.v1alpha1.CheckResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ory_keto_opl_v1alpha1_syntax_service_proto_init() }
func file_ory_keto_opl_v1alpha1_syntax_service_proto_init() {
	if File_ory_keto_opl_v1alpha1_syntax_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDesc), len(file_ory_keto_opl_v1alpha1_syntax_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ory_keto_opl_v1alpha1_syntax_service_proto_goTypes,
		DependencyIndexes: file_ory_keto_opl_v1alpha1_syntax_service_proto_depIdxs,
		MessageInfos:      file_ory_keto_opl_v1alpha1_syntax_service_proto_msgTypes,
	}.Build()
	File_ory_keto_opl_v1alpha1_syntax_service_proto = out.File
	file_ory_keto_opl_v1alpha1_syntax_service_proto_goTypes = nil
	file_ory_keto_opl_v1alpha1_syntax_service_proto_depIdxs = nil
}
