// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: ory/keto/opl/v1alpha1/syntax_service.proto

package opl

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SyntaxServiceClient is the client API for SyntaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyntaxServiceClient interface {
	// Performs a syntax check request.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type syntaxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyntaxServiceClient(cc grpc.ClientConnInterface) SyntaxServiceClient {
	return &syntaxServiceClient{cc}
}

func (c *syntaxServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/ory.keto.opl.v1alpha1.SyntaxService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyntaxServiceServer is the server API for SyntaxService service.
// All implementations should embed UnimplementedSyntaxServiceServer
// for forward compatibility
type SyntaxServiceServer interface {
	// Performs a syntax check request.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
}

// UnimplementedSyntaxServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSyntaxServiceServer struct {
}

func (UnimplementedSyntaxServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}

// UnsafeSyntaxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyntaxServiceServer will
// result in compilation errors.
type UnsafeSyntaxServiceServer interface {
	mustEmbedUnimplementedSyntaxServiceServer()
}

func RegisterSyntaxServiceServer(s grpc.ServiceRegistrar, srv SyntaxServiceServer) {
	s.RegisterService(&SyntaxService_ServiceDesc, srv)
}

func _SyntaxService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyntaxServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ory.keto.opl.v1alpha1.SyntaxService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyntaxServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyntaxService_ServiceDesc is the grpc.ServiceDesc for SyntaxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyntaxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ory.keto.opl.v1alpha1.SyntaxService",
	HandlerType: (*SyntaxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _SyntaxService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ory/keto/opl/v1alpha1/syntax_service.proto",
}
