// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=dts"
// @generated from file ory/keto/opl/v1alpha1/syntax_service.proto (package ory.keto.opl.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckRequest, CheckResponse } from "./syntax_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service that checks the syntax of an OPL file.
 *
 * @generated from service ory.keto.opl.v1alpha1.SyntaxService
 */
export declare const SyntaxService: {
  readonly typeName: "ory.keto.opl.v1alpha1.SyntaxService",
  readonly methods: {
    /**
     * Performs a syntax check request.
     *
     * @generated from rpc ory.keto.opl.v1alpha1.SyntaxService.Check
     */
    readonly check: {
      readonly name: "Check",
      readonly I: typeof CheckRequest,
      readonly O: typeof CheckResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

