blank_issues_enabled: false
contact_links:
  - name: ORY ${PROJECT} Forum
    url: https://github.com/${REPOSITORY}/discussions
    about: Please ask and answer questions here, show your implementations and discuss ideas.
  - name: ORY Chat
    url: https://www.ory.sh/chat
    about: Hang out with other ORY community members and ask and answer questions.
  - name: ORY Support for Business
    url: https://github.com/ory/open-source-support/blob/master/README.md
    about: Buy professional support for ORY ${PROJECT}.
