// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=js,js_import_style=module"
// @generated from file ory/keto/relation_tuples/v1alpha2/check_service.proto (package ory.keto.relation_tuples.v1alpha2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckRequest, CheckResponse } from "./check_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The service that performs authorization checks
 * based on the stored Access Control Lists.
 *
 * This service is part of the [read-APIs](../concepts/25_api-overview.mdx#read-apis).
 *
 * @generated from service ory.keto.relation_tuples.v1alpha2.CheckService
 */
export const CheckService = {
  typeName: "ory.keto.relation_tuples.v1alpha2.CheckService",
  methods: {
    /**
     * Performs an authorization check.
     *
     * @generated from rpc ory.keto.relation_tuples.v1alpha2.CheckService.Check
     */
    check: {
      name: "Check",
      I: CheckRequest,
      O: CheckResponse,
      kind: MethodKind.Unary,
    },
  }
};

