// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=js,js_import_style=module"
// @generated from file ory/keto/relation_tuples/v1alpha2/write_service.proto (package ory.keto.relation_tuples.v1alpha2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteRelationTuplesRequest, DeleteRelationTuplesResponse, TransactRelationTuplesRequest, TransactRelationTuplesResponse } from "./write_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The write service to create and delete Access Control Lists.
 *
 * This service is part of the [write-APIs](../concepts/25_api-overview.mdx#write-apis).
 *
 * @generated from service ory.keto.relation_tuples.v1alpha2.WriteService
 */
export const WriteService = {
  typeName: "ory.keto.relation_tuples.v1alpha2.WriteService",
  methods: {
    /**
     * Writes one or more relationships in a single transaction.
     *
     * @generated from rpc ory.keto.relation_tuples.v1alpha2.WriteService.TransactRelationTuples
     */
    transactRelationTuples: {
      name: "TransactRelationTuples",
      I: TransactRelationTuplesRequest,
      O: TransactRelationTuplesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes relationships based on relation query
     *
     * @generated from rpc ory.keto.relation_tuples.v1alpha2.WriteService.DeleteRelationTuples
     */
    deleteRelationTuples: {
      name: "DeleteRelationTuples",
      I: DeleteRelationTuplesRequest,
      O: DeleteRelationTuplesResponse,
      kind: MethodKind.Unary,
    },
  }
};

