// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: keto/acl/v1alpha1/write_service.proto

package acl

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RelationTupleWriteDelta_Action int32

const (
	// Unspecified.
	// The `WriteRelationTuples` rpc ignores this
	// RelationTupleWriteDelta if an action was unspecified.
	RelationTupleWriteDelta_ACTION_UNSPECIFIED RelationTupleWriteDelta_Action = 0
	// Insertion of a new RelationTuple.
	// It is ignored if already existing.
	RelationTupleWriteDelta_INSERT RelationTupleWriteDelta_Action = 1
	// Deletion of the RelationTuple.
	// It is ignored if it does not exist.
	RelationTupleWriteDelta_DELETE RelationTupleWriteDelta_Action = 4
)

// Enum value maps for RelationTupleWriteDelta_Action.
var (
	RelationTupleWriteDelta_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "INSERT",
		4: "DELETE",
	}
	RelationTupleWriteDelta_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"INSERT":             1,
		"DELETE":             4,
	}
)

func (x RelationTupleWriteDelta_Action) Enum() *RelationTupleWriteDelta_Action {
	p := new(RelationTupleWriteDelta_Action)
	*p = x
	return p
}

func (x RelationTupleWriteDelta_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationTupleWriteDelta_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_keto_acl_v1alpha1_write_service_proto_enumTypes[0].Descriptor()
}

func (RelationTupleWriteDelta_Action) Type() protoreflect.EnumType {
	return &file_keto_acl_v1alpha1_write_service_proto_enumTypes[0]
}

func (x RelationTupleWriteDelta_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationTupleWriteDelta_Action.Descriptor instead.
func (RelationTupleWriteDelta_Action) EnumDescriptor() ([]byte, []int) {
	return file_keto_acl_v1alpha1_write_service_proto_rawDescGZIP(), []int{1, 0}
}

// The request of a WriteService.WriteRelationTuples rpc.
type WriteRelationTuplesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The write delta for the relation tuples operated in one single transaction.
	// Either all actions commit or no change takes effect on error.
	//
	// The tuple's etag is used for a consistent read-modify-write request flow.
	// If the etag is not present, the tuple is not validated against the state
	// of the serverside tuple and get operated anyway.
	RelationTupleDeltas []*RelationTupleWriteDelta `protobuf:"bytes,1,rep,name=relation_tuple_deltas,json=relationTupleDeltas,proto3" json:"relation_tuple_deltas,omitempty"`
}

func (x *WriteRelationTuplesRequest) Reset() {
	*x = WriteRelationTuplesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keto_acl_v1alpha1_write_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRelationTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationTuplesRequest) ProtoMessage() {}

func (x *WriteRelationTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keto_acl_v1alpha1_write_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationTuplesRequest.ProtoReflect.Descriptor instead.
func (*WriteRelationTuplesRequest) Descriptor() ([]byte, []int) {
	return file_keto_acl_v1alpha1_write_service_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRelationTuplesRequest) GetRelationTupleDeltas() []*RelationTupleWriteDelta {
	if x != nil {
		return x.RelationTupleDeltas
	}
	return nil
}

// Write-delta for a WriteRelationTuplesRequest.
type RelationTupleWriteDelta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The action to do on the RelationTuple.
	Action RelationTupleWriteDelta_Action `protobuf:"varint,1,opt,name=action,proto3,enum=keto.acl.v1alpha1.RelationTupleWriteDelta_Action" json:"action,omitempty"`
	// The target RelationTuple.
	RelationTuple *RelationTuple `protobuf:"bytes,2,opt,name=relation_tuple,json=relationTuple,proto3" json:"relation_tuple,omitempty"`
}

func (x *RelationTupleWriteDelta) Reset() {
	*x = RelationTupleWriteDelta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keto_acl_v1alpha1_write_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationTupleWriteDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTupleWriteDelta) ProtoMessage() {}

func (x *RelationTupleWriteDelta) ProtoReflect() protoreflect.Message {
	mi := &file_keto_acl_v1alpha1_write_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTupleWriteDelta.ProtoReflect.Descriptor instead.
func (*RelationTupleWriteDelta) Descriptor() ([]byte, []int) {
	return file_keto_acl_v1alpha1_write_service_proto_rawDescGZIP(), []int{1}
}

func (x *RelationTupleWriteDelta) GetAction() RelationTupleWriteDelta_Action {
	if x != nil {
		return x.Action
	}
	return RelationTupleWriteDelta_ACTION_UNSPECIFIED
}

func (x *RelationTupleWriteDelta) GetRelationTuple() *RelationTuple {
	if x != nil {
		return x.RelationTuple
	}
	return nil
}

// The response of a WriteService.WriteRelationTuples rpc.
type WriteRelationTuplesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of the new latest snapshot tokens of the affected RelationTuple,
	// with the same index as specified in the `relation_tuple_deltas` field of
	// the WriteRelationTuplesRequest request.
	//
	// The snaptoken is nil at the same index
	// if the RelationTupleWriteDelta_Action was DELETE.
	Snaptokens []string `protobuf:"bytes,1,rep,name=snaptokens,proto3" json:"snaptokens,omitempty"`
}

func (x *WriteRelationTuplesResponse) Reset() {
	*x = WriteRelationTuplesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keto_acl_v1alpha1_write_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRelationTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationTuplesResponse) ProtoMessage() {}

func (x *WriteRelationTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keto_acl_v1alpha1_write_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationTuplesResponse.ProtoReflect.Descriptor instead.
func (*WriteRelationTuplesResponse) Descriptor() ([]byte, []int) {
	return file_keto_acl_v1alpha1_write_service_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRelationTuplesResponse) GetSnaptokens() []string {
	if x != nil {
		return x.Snaptokens
	}
	return nil
}

var File_keto_acl_v1alpha1_write_service_proto protoreflect.FileDescriptor

var file_keto_acl_v1alpha1_write_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6b, 0x65, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63,
	0x6c, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1b, 0x6b, 0x65, 0x74, 0x6f,
	0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61, 0x63,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x1a, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5e, 0x0a, 0x15, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x6c, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61,
	0x52, 0x13, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x44,
	0x65, 0x6c, 0x74, 0x61, 0x73, 0x22, 0xe7, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x74,
	0x61, 0x12, 0x49, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x31, 0x2e, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x6c, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0e,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x6c, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x75, 0x70, 0x6c, 0x65, 0x22, 0x38, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x12, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45, 0x52,
	0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x22,
	0x3d, 0x0a, 0x1b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x32, 0x84,
	0x01, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x74, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x2d, 0x2e, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63,
	0x6c, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x6c,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x8e, 0x01, 0x0a, 0x18, 0x73, 0x68, 0x2e, 0x6f, 0x72, 0x79,
	0x2e, 0x6b, 0x65, 0x74, 0x6f, 0x2e, 0x61, 0x63, 0x6c, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x42, 0x11, 0x57, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x79, 0x2f, 0x6b, 0x65, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6b, 0x65, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x3b, 0x61, 0x63, 0x6c, 0xaa, 0x02, 0x15, 0x4f, 0x72, 0x79, 0x2e, 0x4b, 0x65, 0x74,
	0x6f, 0x2e, 0x41, 0x63, 0x6c, 0x2e, 0x56, 0x31, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x31, 0xca, 0x02,
	0x15, 0x4f, 0x72, 0x79, 0x5c, 0x4b, 0x65, 0x74, 0x6f, 0x5c, 0x41, 0x63, 0x6c, 0x5c, 0x56, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keto_acl_v1alpha1_write_service_proto_rawDescOnce sync.Once
	file_keto_acl_v1alpha1_write_service_proto_rawDescData = file_keto_acl_v1alpha1_write_service_proto_rawDesc
)

func file_keto_acl_v1alpha1_write_service_proto_rawDescGZIP() []byte {
	file_keto_acl_v1alpha1_write_service_proto_rawDescOnce.Do(func() {
		file_keto_acl_v1alpha1_write_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_keto_acl_v1alpha1_write_service_proto_rawDescData)
	})
	return file_keto_acl_v1alpha1_write_service_proto_rawDescData
}

var file_keto_acl_v1alpha1_write_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keto_acl_v1alpha1_write_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_keto_acl_v1alpha1_write_service_proto_goTypes = []interface{}{
	(RelationTupleWriteDelta_Action)(0), // 0: keto.acl.v1alpha1.RelationTupleWriteDelta.Action
	(*WriteRelationTuplesRequest)(nil),  // 1: keto.acl.v1alpha1.WriteRelationTuplesRequest
	(*RelationTupleWriteDelta)(nil),     // 2: keto.acl.v1alpha1.RelationTupleWriteDelta
	(*WriteRelationTuplesResponse)(nil), // 3: keto.acl.v1alpha1.WriteRelationTuplesResponse
	(*RelationTuple)(nil),               // 4: keto.acl.v1alpha1.RelationTuple
}
var file_keto_acl_v1alpha1_write_service_proto_depIdxs = []int32{
	2, // 0: keto.acl.v1alpha1.WriteRelationTuplesRequest.relation_tuple_deltas:type_name -> keto.acl.v1alpha1.RelationTupleWriteDelta
	0, // 1: keto.acl.v1alpha1.RelationTupleWriteDelta.action:type_name -> keto.acl.v1alpha1.RelationTupleWriteDelta.Action
	4, // 2: keto.acl.v1alpha1.RelationTupleWriteDelta.relation_tuple:type_name -> keto.acl.v1alpha1.RelationTuple
	1, // 3: keto.acl.v1alpha1.WriteService.WriteRelationTuples:input_type -> keto.acl.v1alpha1.WriteRelationTuplesRequest
	3, // 4: keto.acl.v1alpha1.WriteService.WriteRelationTuples:output_type -> keto.acl.v1alpha1.WriteRelationTuplesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_keto_acl_v1alpha1_write_service_proto_init() }
func file_keto_acl_v1alpha1_write_service_proto_init() {
	if File_keto_acl_v1alpha1_write_service_proto != nil {
		return
	}
	file_keto_acl_v1alpha1_acl_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_keto_acl_v1alpha1_write_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRelationTuplesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keto_acl_v1alpha1_write_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationTupleWriteDelta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keto_acl_v1alpha1_write_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRelationTuplesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keto_acl_v1alpha1_write_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keto_acl_v1alpha1_write_service_proto_goTypes,
		DependencyIndexes: file_keto_acl_v1alpha1_write_service_proto_depIdxs,
		EnumInfos:         file_keto_acl_v1alpha1_write_service_proto_enumTypes,
		MessageInfos:      file_keto_acl_v1alpha1_write_service_proto_msgTypes,
	}.Build()
	File_keto_acl_v1alpha1_write_service_proto = out.File
	file_keto_acl_v1alpha1_write_service_proto_rawDesc = nil
	file_keto_acl_v1alpha1_write_service_proto_goTypes = nil
	file_keto_acl_v1alpha1_write_service_proto_depIdxs = nil
}
