FROM alpine:3.16.3

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin

RUN apk --no-cache --latest upgrade
RUN apk --no-cache --upgrade --latest add ca-certificates

COPY keto /usr/bin/keto

USER ory

ENTRYPOINT ["keto"]
CMD ["serve"]
