/*
 * Ory Keto API
 *
 * Documentation for all of Ory Keto's REST APIs. gRPC is documented separately.
 *
 * API version:
 * Contact: hi@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BatchCheckPermissionBody struct for BatchCheckPermissionBody
type BatchCheckPermissionBody struct {
	Tuples []Relationship `json:"tuples,omitempty"`
}

// NewBatchCheckPermissionBody instantiates a new BatchCheckPermissionBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchCheckPermissionBody() *BatchCheckPermissionBody {
	this := BatchCheckPermissionBody{}
	return &this
}

// NewBatchCheckPermissionBodyWithDefaults instantiates a new BatchCheckPermissionBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchCheckPermissionBodyWithDefaults() *BatchCheckPermissionBody {
	this := BatchCheckPermissionBody{}
	return &this
}

// GetTuples returns the Tuples field value if set, zero value otherwise.
func (o *BatchCheckPermissionBody) GetTuples() []Relationship {
	if o == nil || o.Tuples == nil {
		var ret []Relationship
		return ret
	}
	return o.Tuples
}

// GetTuplesOk returns a tuple with the Tuples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchCheckPermissionBody) GetTuplesOk() ([]Relationship, bool) {
	if o == nil || o.Tuples == nil {
		return nil, false
	}
	return o.Tuples, true
}

// HasTuples returns a boolean if a field has been set.
func (o *BatchCheckPermissionBody) HasTuples() bool {
	if o != nil && o.Tuples != nil {
		return true
	}

	return false
}

// SetTuples gets a reference to the given []Relationship and assigns it to the Tuples field.
func (o *BatchCheckPermissionBody) SetTuples(v []Relationship) {
	o.Tuples = v
}

func (o BatchCheckPermissionBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tuples != nil {
		toSerialize["tuples"] = o.Tuples
	}
	return json.Marshal(toSerialize)
}

type NullableBatchCheckPermissionBody struct {
	value *BatchCheckPermissionBody
	isSet bool
}

func (v NullableBatchCheckPermissionBody) Get() *BatchCheckPermissionBody {
	return v.value
}

func (v *NullableBatchCheckPermissionBody) Set(val *BatchCheckPermissionBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchCheckPermissionBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchCheckPermissionBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchCheckPermissionBody(val *BatchCheckPermissionBody) *NullableBatchCheckPermissionBody {
	return &NullableBatchCheckPermissionBody{value: val, isSet: true}
}

func (v NullableBatchCheckPermissionBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchCheckPermissionBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
