/*
 * Ory Keto API
 *
 * Documentation for all of Ory Keto's REST APIs. gRPC is documented separately.
 *
 * API version:
 * Contact: hi@ory.sh
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"fmt"
)

// RelationshipDeltaAction  - ACTION_UNSPECIFIED: Unspecified. The `TransactRelationTuples` RPC ignores this RelationTupleDelta if an action was unspecified.  - insert: Insertion of a new RelationTuple. It is ignored if already existing.  - delete: Deletion of the RelationTuple. It is ignored if it does not exist.
type RelationshipDeltaAction string

// List of relationshipDelta.Action
const (
	RELATIONSHIPDELTAACTION_ACTION_UNSPECIFIED RelationshipDeltaAction = "ACTION_UNSPECIFIED"
	RELATIONSHIPDELTAACTION_INSERT             RelationshipDeltaAction = "insert"
	RELATIONSHIPDELTAACTION_DELETE             RelationshipDeltaAction = "delete"
)

func (v *RelationshipDeltaAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RelationshipDeltaAction(value)
	for _, existing := range []RelationshipDeltaAction{"ACTION_UNSPECIFIED", "insert", "delete"} {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RelationshipDeltaAction", value)
}

// Ptr returns reference to relationshipDelta.Action value
func (v RelationshipDeltaAction) Ptr() *RelationshipDeltaAction {
	return &v
}

type NullableRelationshipDeltaAction struct {
	value *RelationshipDeltaAction
	isSet bool
}

func (v NullableRelationshipDeltaAction) Get() *RelationshipDeltaAction {
	return v.value
}

func (v *NullableRelationshipDeltaAction) Set(val *RelationshipDeltaAction) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationshipDeltaAction) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationshipDeltaAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationshipDeltaAction(val *RelationshipDeltaAction) *NullableRelationshipDeltaAction {
	return &NullableRelationshipDeltaAction{value: val, isSet: true}
}

func (v NullableRelationshipDeltaAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationshipDeltaAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
