// Code generated by go-swagger; DO NOT EDIT.

package engines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ory/keto/internal/httpclient/models"
)

// UpsertOryAccessControlPolicyReader is a Reader for the UpsertOryAccessControlPolicy structure.
type UpsertOryAccessControlPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpsertOryAccessControlPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpsertOryAccessControlPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewUpsertOryAccessControlPolicyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpsertOryAccessControlPolicyOK creates a UpsertOryAccessControlPolicyOK with default headers values
func NewUpsertOryAccessControlPolicyOK() *UpsertOryAccessControlPolicyOK {
	return &UpsertOryAccessControlPolicyOK{}
}

/* UpsertOryAccessControlPolicyOK describes a response with status code 200, with default header values.

oryAccessControlPolicy
*/
type UpsertOryAccessControlPolicyOK struct {
	Payload *models.OryAccessControlPolicy
}

func (o *UpsertOryAccessControlPolicyOK) Error() string {
	return fmt.Sprintf("[PUT /engines/acp/ory/{flavor}/policies][%d] upsertOryAccessControlPolicyOK  %+v", 200, o.Payload)
}
func (o *UpsertOryAccessControlPolicyOK) GetPayload() *models.OryAccessControlPolicy {
	return o.Payload
}

func (o *UpsertOryAccessControlPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OryAccessControlPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpsertOryAccessControlPolicyInternalServerError creates a UpsertOryAccessControlPolicyInternalServerError with default headers values
func NewUpsertOryAccessControlPolicyInternalServerError() *UpsertOryAccessControlPolicyInternalServerError {
	return &UpsertOryAccessControlPolicyInternalServerError{}
}

/* UpsertOryAccessControlPolicyInternalServerError describes a response with status code 500, with default header values.

The standard error format
*/
type UpsertOryAccessControlPolicyInternalServerError struct {
	Payload *UpsertOryAccessControlPolicyInternalServerErrorBody
}

func (o *UpsertOryAccessControlPolicyInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /engines/acp/ory/{flavor}/policies][%d] upsertOryAccessControlPolicyInternalServerError  %+v", 500, o.Payload)
}
func (o *UpsertOryAccessControlPolicyInternalServerError) GetPayload() *UpsertOryAccessControlPolicyInternalServerErrorBody {
	return o.Payload
}

func (o *UpsertOryAccessControlPolicyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpsertOryAccessControlPolicyInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*UpsertOryAccessControlPolicyInternalServerErrorBody upsert ory access control policy internal server error body
swagger:model UpsertOryAccessControlPolicyInternalServerErrorBody
*/
type UpsertOryAccessControlPolicyInternalServerErrorBody struct {

	// code
	Code int64 `json:"code,omitempty"`

	// details
	Details []interface{} `json:"details"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// request
	Request string `json:"request,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this upsert ory access control policy internal server error body
func (o *UpsertOryAccessControlPolicyInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upsert ory access control policy internal server error body based on context it is used
func (o *UpsertOryAccessControlPolicyInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpsertOryAccessControlPolicyInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpsertOryAccessControlPolicyInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res UpsertOryAccessControlPolicyInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
