// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DoOryAccessControlPoliciesAllowReader DoOryAccessControlPoliciesAllowReader is a Reader for the DoOryAccessControlPoliciesAllow structure.
// swagger:model DoOryAccessControlPoliciesAllowReader
type DoOryAccessControlPoliciesAllowReader interface{}
