name: Format

on:
  pull_request:
  push:
  merge_group:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          check-latest: true
      - run: make format
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
