name: "Close Stale Issues"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    if: github.repository_owner == 'ory'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            Thank you for opening this issue. It appears that the request for more information (e.g. providing the software version, providing logs, ...) has not yet been completed. Therefore this issue will be automatically
            closed in 7 days, assuming that the issue has been resolved.
          stale-pr-message: |
            Thank you for opening this pull request. It appears that a request for e.g. information has not yet been completed. Therefore this issue will be automatically
            closed in 7 days, assuming that the proposed change is no longer required or has otherwise been resolved.
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          only-labels: 'needs more info'
          days-before-stale: 7
          days-before-close: 7
